include:
  - path: ./app-1-basic/vulnerable/docker-compose.yml
    project_directory: ./app-1-basic/vulnerable
  - path: ./app-1-basic/fixed/docker-compose.yml
    project_directory: ./app-1-basic/fixed
  - path: ./app-2-graphql/vulnerable/docker-compose.yml
    project_directory: ./app-2-graphql/vulnerable

services:
  landing:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./landing:/usr/share/nginx/html:ro
    restart: unless-stopped
