version: '3.8'

services:
  https-logger:
    build: .
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
      - ./captures:/captures
    networks:
      - https-traffic-net

  https-nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - https-logger
    networks:
      - https-traffic-net

networks:
  https-traffic-net:
    driver: bridge
